### ISSUE TITLE
Installing/Using Seaborn

### ISSUE THREAD

**Issue by hoeferjanka** [hadasvolk/CompLabNGS#12]
I have big issues completing the installation of seaborn. In Jupyterlab it does not let me install it and i have no other way of using python...

import seaborn as sns
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 import seaborn as sns

ModuleNotFoundError: No module named 'seaborn'

I am quite stuck with this issue and i do not know how else i can solve it.

**Comment by hadasvolk** [comment]
I need more details. How did you try to install it?
You can probably do inside Jupyter
```bash
!pip install seaborn
```

**Comment by hoeferjanka** [comment]
I tried to install it using different commands i found online. Everytime i get the same Error.


---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[3], line 1
----> 1 get_ipython().system('pip install seaborn')

File /lib/python3.11/site-packages/IPython/core/interactiveshell.py:2653, in InteractiveShell.system_piped(self, cmd)
   2648     raise OSError("Background processes not supported.")
   2650 # we explicitly do NOT return the subprocess status code, because
   2651 # a non-None value would trigger :func:`sys.displayhook` calls.
   2652 # Instead, we store the exit_code in user_ns.
-> 2653 self.user_ns['_exit_code'] = system(self.var_expand(cmd, depth=1))

File /lib/python3.11/site-packages/IPython/utils/_process_emscripten.py:11, in system(cmd)
     10 def system(cmd):
---> 11     raise OSError("Not available")

OSError: Not available

**Comment by hadasvolk** [comment]
Please provide detailed description of the process you took. I'm unable to understand the problem from thus error message
