### ISSUE TITLE
Qualimap installation

### ISSUE THREAD

**Issue by ranelmalka100** [hadasvolk/CompLabNGS#13]
Hello :) 

I couldn't install Qualimap and I don't know why. 
I've tried to install it by this manual - http://qualimap.conesalab.org/doc_html/intro.html#installation, with no success. 
I've tried to run the qualimap command line inside qualimap directory  - 
`qualimap_v2.3 rnaseq -bam /home/nofar/CompLabNGS/8-RNA1/sortedAligned.sortedByCoord.out.bam
-gtf /home/nofar/CompLabNGS/8-RNA1/S288C_reference_annotation_proc.gtf`
with no success.. 

I would be happy to get help, 
Thanks in advance :)

**Comment by hadasvolk** [comment]
Hello, the link you provided appears to be broken, but why not use anaconda to facilitate the installation?

**Comment by ranelmalka100** [comment]
Thank you for the quick reply :) I will try

**Comment by ranelmalka100** [comment]
In another issue regarding these hw, my IGV couldn't load the reference genome of S288C, but the STARsortedbam file was successfully uploaded. Do you have an idea why?

**Comment by hadasvolk** [comment]
Not without more information no
