### ISSUE TITLE
Final assignment

### ISSUE THREAD

**Issue by tehilayehudai** [hadasvolk/CompLabNGS#18]
Hi,
In the important notes section, you wrote that any redirection to data outside the notebook would result in a lowering of the grade. but you also mentioned that we should include figures. Can we attach a folder with the results outputs images so they will appear inside the notebook?

**Comment by hadasvolk** [comment]
Yes
What I meant is don't tell me look there and there. You can embed the figure in the notebook

**Comment by tehilayehudai** [comment]
Thanks!
And two more questions.. 1. We wrote the bash commands with ```bash``` in the markdown cell and not with "!" , it is OK? 
2. About the Python analysis - Do you want us to attach the CSV files on which the analysis is based?  Or should we only attach figures like the volcano plot and clustermap?

**Comment by hadasvolk** [comment]
1. Ok
2. Attach the csv, but also add representative rows from the data frame in the notebook (head/topgenes...)

**Comment by JOSHKAHN96** [comment]
So if we write the bash commands in a markdown cells, does that mean we can just attach the kallisto output (.tsv) needed for the Python code in the file we send you?

**Comment by hadasvolk** [comment]
Attach the tsv, but also add representative rows from the data frame in the notebook (head/topgenes...)
