### ISSUE TITLE
A question regarding the home exercises in the course

### ISSUE THREAD

**Issue by Ataliai** [hadasvolk/CompLabNGS#20]
Hi Hades, 

According to what is written in CompLabNGS, our grade also consists of 30 points of homework that must be completed. In addition, it says that you must submit at least 8 assignments to pass the course. I submitted 8 exercises, but the model does not show a passing grade (no grade at all) on any of them. Can it be assumed that everything is fine and that there is no need to also submit the exercise that I did not submit?

Thanks, 
Atalia

**Comment by hadasvolk** [comment]
Yes, it is fine
I haven't graded yet, no worries
