### ISSUE TITLE
Issue with interpreting the ILLUMINACLIP parameters (Homework 3, Q4)

### ISSUE THREAD

**Issue by ILYAKAZHDAN** [hadasvolk/CompLabNGS#22]
Dear CompLabNGS Course Community,

I have an inquiry that I would like to share (and discuss) with you about Homework 3, Question 4.

I have successfully ran the trimmomatic command using ILLUMINACLIP parameter in order to cleave the adapter from the read,
since the "Adapter Content" plot showed it. However, I am still struggling to understand the meaning beyond the parameters we use to run it (2:30:10) in "ILLUMINACLIP:NexteraPE-PE.fa:2:30:10". 

Here's what I understand, based on reading the documentation about ILLUMINACLIP:
- 2, stands for the maximum number of mismatches in the adapter
- 30, is the minimal threshold score to cleave the palindromic adapters
- 10, is the minimal threshold score for matches between the adapter (at the end) and the read itself

Nonetheless, I'm still quite uncertain and was not able to find the answer about why do we consider 10 (or the range 7-15) as the "default" for trimming the adapter at the ends? Is there any particular reason that we chose this number? My assumption was that at both ends, a score around 10 would represent a bad quality, which highly contrasts the quality for the rest of the sequence (assuming that it has a general average high quality scores of 30+.) Perhaps this could justify the removal of the Nextera adapter? Is there another reason behind the meaning of this number?

I would like to discuss this topic with you to try to resolve this issue and better understand how does this parameter work in trimmomatic. 

Kind regards,
Ilya

**Comment by ILYAKAZHDAN** [comment]
Also, I'd like to discuss the same thing, but for 30 (the minimal threshold score to cleave the palindromic adapters.)
Why did we choose this score as the default? Is there a similar reason behind this?

**Comment by hadasvolk** [comment]
Hi Ilya, let's do a breakdown of ILLUMINACLIP parameters and understand there meaning
`ILLUMINACLIP:NexteraPE-PE.fa:2:30:10`  

1. Seed Mismatches (2):

- Definition: The maximum number of mismatches allowed in the initial matching seed segment when aligning adapters to reads.

- Implication: A value of 2 allows up to two mismatches in the seed region. This balances sensitivity (detecting true adapter sequences) and specificity (avoiding false positives).

2. Palindrome Clip Threshold (30):

- Definition: The minimum sum of quality scores required for a palindrome (i.e., when adapters are present in both forward and reverse reads in a paired-end setup) to trigger clipping.

- Implication: A higher threshold like 30 ensures that only high-confidence adapter matches result in clipping, reducing the chance of mistakenly trimming genuine low-quality bases.

3. Simple Clip Threshold (10):

- Definition: The minimum sum of quality scores required for a straightforward (non-palindromic) adapter match to trigger clipping.

- Implication: A threshold of 10 allows for the removal of adapters even if the overall quality in the matched region is relatively low, which is common at the ends of reads where adapters are more likely to be found.


We start with the empirical recommendations from Illumina utilizing the default 2:30:10 parameters for initial trimming, as they are optimized for general use cases and provide a good balance between sensitivity and specificity.
If you observe that the default settings are either not trimming all adapter sequences effectively or are trimming too much of the genuine data, consider tweaking the simple clip threshold within a broader range. This adjustment should be guided by subsequent quality assessments (e.g., using FastQC) to ensure optimal trimming performance.

I hope this answers your good question
