### ISSUE TITLE
Request to change the rooms following asbestos works

### ISSUE THREAD

**Issue by ILYAKAZHDAN** [hadasvolk/CompLabNGS#24]
Hi Hadas,
Following the faculty announcement that was made about the asbestos works, I'd like to ask if we could move our classes in the next two weeks (15/12 and 22/12) to another lecture hall in another building (possibly) due to safety concerns?

Thanks,
Ilya

**Comment by hadasvolk** [comment]
Hi Ilya, haven't gotten this memo. I'll look into it
