### ISSUE TITLE
Issues with Part II in Homework 6

### ISSUE THREAD

**Issue by ILYAKAZHDAN** [hadasvolk/CompLabNGS#25]
Hi Hadas,
For Part II, we were requested to configure configManta.py to run 'Manta-SV'.
However, I got this error:
"-bash: HQ: No such file or directory"

I believe this error can be attributed to the fact that configManta.py is not installed in Linux.
Therefore, I tried installing it, using this command, but it failed:
"conda install manta"

This error was given: "Error while loading conda entry point: conda-libmamba-solver (libarchive.so.20: cannot open shared object file: No such file or directory)"

Then, I turned to [Manta's GitHub](https://github.com/Illumina/manta/blob/master/docs/userGuide/installation.md#linux-package-additions) and followed the installation instructions to install the python script, but it didn't work as well, returning a 404 error (which probably means that the download package doesn't exist in the server)

This command I used for this was:
"wget https://github.com/Illumina/manta/releases/download/v1331/manta-1331.release_src.tar.bz2"

Could you provide us with clearer instructions of how do we install Manta? 
(Since it's necessary for Part II, and configuring won't work until we download it.)

Kind regards,
Ilya

**Comment by hadasvolk** [comment]
Hi Ilya, the initial error you pasted `-bash: HQ: No such file or directory` does not mean `configManta.py` is not installed, rather that there is no file or directory in the current working directory named `HQ`

Try installing manta using conda and specifying the channel to download from
`conda install bioconda::manta`

Test your installation `configManta.py --help`

**Comment by ILYAKAZHDAN** [comment]
Hi Hadas,
I tried this in my conda environment, but I'm still getting an error:

"(base) ilya_k@ILYA-PC:~$ conda install bioconda::manta
Error while loading conda entry point: conda-libmamba-solver (libarchive.so.20: cannot open shared object file: No such file or directory)
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: \ failed"

Looks like it attempted to install it using the bioconda channel several times like you suggested, but I'm not certain it worked.

When trying "configManta.py --help", it told that the command doesn't exist:
"configManta.py: command not found"

Is there another working workaround?

Thanks,
Ilya

**Comment by hadasvolk** [comment]
you might have conflicting dependincies in your base enviorment. you could try to create a new conda enviorment for manta
`conda create -n manta bioconda::manta;
conda activate manta`

if this does not you should be able to download manta from its github repo, unpack and run
