### ISSUE TITLE
Ex6- installing GATK

### ISSUE THREAD

**Issue by shovalsegal** [hadasvolk/CompLabNGS#3]
I'm having trouble installing GATK, this is what i did:
1. downloaded GATK from their website, put it in my repository and extracted the zip fie.
2. tried to change the PATH in the ".bashrc" file and run the command "gatk- register".
that didn't work.

also tried to download the gatk via conda. that didn't worked either.

so i would appreciate some help on how to install gatk.

**Comment by hadasvolk** [comment]
Hi,

Are you working on an HPC/cluster or your own linux machine? Have you tried to install gatk using conda?
```bash
conda create -n gatk -c bioconda gatk
```

If you are working on an HPC system you might have gatk already avilable for you on the module system.

If you prefer to download and install gatk manually you should make sure you have all needed dependencies installed, e.g. java and perl. You should follow the instructions in the gatk website and forum for detailed troubleshooting and generating a registration codes

**Comment by shovalsegal** [comment]
I'm working on my own Linux machine, following this instructions [https://gatk.broadinstitute.org/hc/en-us/articles/360041320571--How-to-Install-all-software-packages-required-to-follow-the-GATK-Best-Practices](url).
where all the programs should be downloaded to?
and regarding to updating the PATH, it supposed to reach the main folder or a sub folder?

**Comment by hadasvolk** [comment]
You are free to download software wherever you want. Usually it is a good practice to have a dedicated place for all your tools.

Your PATH should contain the full path to directory holding the binary 
https://linuxize.com/post/how-to-add-directory-to-path-in-linux/
