### ISSUE TITLE
igv problem

### ISSUE THREAD

**Issue by shovalsegal** [hadasvolk/CompLabNGS#5]
hi,
igv started looking blurry, very strange, and not possible to work with.
I tried update, install again, closing, and opening ubuntu and searching online, but that didn't work.
If someone is familiar with this and has a solution that will be great.
![Untitled](https://github.com/hadasvolk/CompLabNGS/assets/138568866/31c667f4-c19c-488d-a5c6-bd750ce8dc3c)

**Comment by hadasvolk** [comment]
Oh gee, very strange
Are you working with WSL? Maybe download the native Windows IGV application, if it is relevant for you.

Give some background on the setup you have (wsl-ubuntu? remote server?). I might be able to help more

**Comment by shovalsegal** [comment]
WSL, Ubuntu, it worked fine until that suddenly happened

**Comment by hadasvolk** [comment]
Cool
So try and use the native windows application from [here](https://igv.org/doc/desktop/#DownloadPage/)

Let me know if this works better for you
