### ISSUE TITLE
Ex8 Q3

### ISSUE THREAD

**Issue by shovalsegal** [hadasvolk/CompLabNGS#6]
I think I did things right, but I can't find this genes on IGV (YDL083c    YEL003W    YKL180W    YNL162W).
I uploaded the reference genome file - S288C_reference_sequence_R64-2-1_20150113.fasta
the annotation - S288C_reference_annotation_proc.gff
and the indexed (by samtools) STAR BAM file - star_mapAligned.sortedByCoord.out.bam

Where I might be wrong?

**Comment by hadasvolk** [comment]
I'm not sure, sounds like you did right
Can you upload an IGV screenshot for region `ChrIV:304,926-309,789`?

**Comment by shovalsegal** [comment]
ok, now its working, i can find the genes.
ty
