### ISSUE TITLE
cant properly install QUAST

### ISSUE THREAD

**Issue by RonSverdlov** [hadasvolk/CompLabNGS#7]
i used QUAST 5.2.0 manual to try and install QUAST, asked chatgpt for help and googled how to install it. i installed a bunch of packages that I'm not sure if they are correct. i also don't understand what do you mean running quast on assembly 4. I eventually managed to get some sort of quast command to work,  I start the command with "python quast.py" and I continue putting the file directories of the contings and scaffolds, this results in a new directory with nothing in it other than the log file which states a bunch of different errors regarding utf-8 codec and some more unclear errors.
sorry if I spill too much but I'm in a little frustration after a few hours of trying to figure it out. is there a method to start from scratch, to understand how to install/access/use assembly4 (when did you talk about it?) and also quast?

**Comment by hadasvolk** [comment]
Have you attempted to install via anaconda? Manual installation can be cumbersome and difficult to debug, I agree

```bash
conda create -n l7 -c bioconda quast busco
conda activate l7
quast --version
```

**Comment by hadasvolk** [comment]
@RonSverdlov I assume you managed to get things working
